
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
some_password: welcome
smaPassword: 3152GameOn!
darkSkyAPI: e79dd2f771e1486375089ebe66afe15c